# Generated by Django 4.0 on 2023-02-22 17:28

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0002_engine_vehicle_model_vehicle_engine_vehicle_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Seller Name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['-name'], 'verbose_name': 'Vehicle Model', 'verbose_name_plural': 'Vehicle Models'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Buick'), (2, 'Cadillac'), (3, 'Chevrolet')], null=True, verbose_name='Vehicle Make/Brand'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['name'], name='chapter_3_v_name_7ccb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['-name'], name='desc_name_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.functions.text.Lower('name'), descending=True), name='lower_name_idx'),
        ),
        migrations.AddField(
            model_name='seller',
            name='vehicle',
            field=models.ManyToManyField(blank=True, related_name='vehicle_sellers', related_query_name='vehicle_seller', to='chapter_3.Vehicle', verbose_name='Vehicles'),
        ),
    ]
