# Generated by Django 4.0 on 2023-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0003_seller_alter_vehiclemodel_options_vehicle_make_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='engine2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Engine')),
            ],
            options={
                'db_table': 'chapter_3_practice_engine',
            },
        ),
    ]
